### ISSUE TITLE
Allow build-arg substitution in artifact paths

### ISSUE THREAD

**Issue by adamperlin** [Azure/dalec#171]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

It is not uncommon to have output binary paths which depend on build-args like `TARGETARCH`, `TARGETOS`, etc. It would be ideal if we could do something like:

```yaml
artifacts:
    binaries:
      mysrc/out/${TARGETARCH}/bin:
```
when describing output artifacts in Dalec. I believe this would  be a simple expansion to the current build-arg substitution phase.

### Are you willing to submit PRs to contribute to this feature request?

- [X] Yes, I am willing to implement it.
