### ISSUE TITLE
[REQ] Built-in Support for golang sources

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#180]
### What kind of request is this?

New feature

## Background

Today all the source types we support have direct `llb` equivalents.
Given that we support generating sources from a container build we can effectively support any kind of source.

However, we've found that while it is possible to support every kind of source, it can be tedious, error prone, and cause a lot of duplication for when using go modules.
Truly this is going to be the case for any language that has its own package management for resolving dependencies.
I am specifically targeting go modules because we have real-world usage of these right now and understand the pain points well.

## Problem

The crux of the issue for go modules is the need to download module dependencies as another source, since we disable network access during the build phase.
Today that means we end up with specs like this:

```yaml
sources:
  myProject:
    git: # the actual go module
      url: https://github.com/cpuguy83/myproject.git
      commit: deadbeef
  gomods: # Fetch the go module dependencies
    path: /build/cache
    image:
      ref: golang:1.21
      cmd:
        dir: /build/src
        mounts:
          - dest: /buildsrc
            spec:
              git:
                url: https://github.com/cpuguy83/myproject.git
                commit: deadbeef
        steps:
          - command: go mod download
            env:
              GOMODCACHE: /build/cache

build:
  steps:
    - command: |
        export GOMODCACHE="$(pwd)/gomods"

        # Build the project
```

Some of the duplication can be cleaned up by using yaml anchors, but that's only really taking care of the smallest chunk of code in that block.
Also most people would have to look up the right syntax to use a yaml anchor every time they make one, which is not a great experience to force on folks (nice that it exists but we should be able to do better).

If you have multiple go modules in a build, now you need to manage all of those dependencies, and the module directory for that.

## Proposal

Add a source to for go modules.
The go struct would look something like this:

```go
type SourceGomod struct {
	// From is how to fetch the origin source
	// This is optional and you may opt instead to provide just the module name
	From *Source `json:"from,omitempty" yaml:"from,omitempty"`

	// Name is the name of the full name of the module that go would use to fetch the module.
	// Either `name` OR `FROM` must be specified, but not both.
	// e.g. "github.com/Azure/daelc@v0.1.0"
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
}
```

In order to fetch go modules, a target handler (eg. `mariner2`) needs to provide an image with `go` (and minimally `git`) in `$PATH`
Dalec will manage the go module directory.
If multiple gomod sources are provided, a single go modules directory will be mounted into each fetch so there is only a single go module.

During the build phase we will inject the modules into `/go/pkg/mod`.
Presumably the target handler can inject a custom path in as needed.

The user will still need to specify go as a build dependency, or otherwise make sure go is available during the build phase.

## Known issues not resolved

One thing not accounted for in this proposal (and also not handled by any other means), is sometimes someone would want to patch `go.mod` before fetching modules.
Since we patch during the build phase (or at least this is what we would do for typical packaging builds) this presents a problem.
I'm not sure we need to solve that problem with this change since its not a new problem.

Some thing we've thrown around as an idea to solving this is to apply patches twice.
First we patch while pulling modules, but then discard the diff.
Then patch again during build.
Alternatively we could just allow people to specify patches that get applied before build and annotate that in packaging specs (where applicable).

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
