### ISSUE TITLE
[BUG] failure to build for target mariner2/container when setting a version specific of a runtime dependency.

### ISSUE THREAD

**Issue by DannyBrito** [Azure/dalec#193]
### Expected Behavior

[BUG] failure to build for target `mariner2/container` when setting a version specific of a runtime dependency.
However using target `mariner2/container/depsonly` works just fine

### Actual Behavior

```
#11 Install RPMs
#11 0.300 Loaded plugin: tdnfrepogpgcheck
#11 0.312 Setting options:
#11 0.312       nogpgcheck = 1
#11 0.312       reposdir = /etc/yum.repos.d
#11 6.029 1. nothing provides vim-8.2.4743 needed by <placeholder>
#11 6.029 Found 1 problem(s) while resolving
#11 6.029 Error(1301) : Solv general runtime error
#11 ERROR: process "sh -c /tmp/install.sh" did not complete successfully: exit code: 21
------
 > Install RPMs:
0.300 Loaded plugin: tdnfrepogpgcheck
0.312 Setting options:
0.312   nogpgcheck = 1
0.312   reposdir = /etc/yum.repos.d
6.029 1. nothing provides vim-8.2.4743 needed by <placeholder>
6.029 Found 1 problem(s) while resolving
6.029 Error(1301) : Solv general runtime error
------
ERROR: failed to solve: process "sh -c /tmp/install.sh" did not complete successfully: exit code: 21
```

### Steps To Reproduce

Dalec Spec example used
tried with 0.2.0 and 0.1.0
```
# syntax=ghcr.io/azure/dalec/frontend:0.2.0
args:
  VERSION: v1.2.0

name: <placeholder>
packager: <placeholder>
vendor: <placeholder>
license: <placeholder>
website: <placeholder>
description: <placeholder>
x-image-name: <placeholder>

version: ${VERSION}
revision: 1

dependencies:
  runtime:
    "vim-8.2.4743" : []
```
Using `docker buildx build -f spec.yml --load -t <tag> .` using default buildx

 Using target `mariner2/container/depsonly` against same Spec works just fine and exploring container, I could verify that specified dep was of required version.

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by cpuguy83** [comment]
```
dependencies:
  runtime:
    "vim" : ["=8.2.4743"]
```

Though that's not likely to work either because of how package versions are pruned.
For instance, here's the versions of `vim` currently in the jammy repos:

```console
$ apt-cache madison vim
       vim | 2:9.0.0749-0york0~22.04 | https://ppa.launchpadcontent.net/jonathonf/vim/ubuntu jammy/main amd64 Packages
       vim | 2:8.2.3995-1ubuntu2.16 | http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
       vim | 2:8.2.3995-1ubuntu2.16 | http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages
       vim | 2:8.2.3995-1ubuntu2 | http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

Usually for such dependencies you use something like a `>=` operator.
That said, it doesn't look like we are including these constraints in the rpm spec we generate currently for some reason.

**Comment by cpuguy83** [comment]
Actually, it is applying it, but something weird is going on with the yaml unmarshaller...
This is the correct format:

```yaml
dependencies:
  runtime:
    vim: 
      version:
        - ">= 8.2.4743"
```

But the unmarshaller is throwing an error.

**Comment by cpuguy83** [comment]
Sorry, I'm making myself crazy here forgetting I have some changes in my local checkout in this area.

**Comment by cpuguy83** [comment]
Ok, so the correct format here (with what's been released and what's in main currently! 😄 ) is 

```yaml
dependencies:
  runtime:
    "vim" : ["=8.2.4743"]
```

But what you probably want is this (or something close to it):

```yaml
dependencies:
  runtime:
    "vim" : [">= 8.2"]
```
