### ISSUE TITLE
[REQ] Add extra validation on patching block for dalec spec and failure if trying to patch not existing source

### ISSUE THREAD

**Issue by DannyBrito** [Azure/dalec#194]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

It would be great if the dalec spec had more validation and error handling for this possible scenario, where writing a spec and trying to include source patches. This scenario is totally the user mistake, but I think dalec could raise this warning of possible something wrong.

```yml
# syntax=ghcr.io/azure/dalec/frontend:0.2.0
sources:
  workload-identity:
    git:
      url: <placeholder>
      commit: <placeholder>
  patch_x:
    http:
      url: <placeholder>.patch
patches:
  src:
    - source: patch_x
   ```

The issue on this snippet is telling spec we want to patch nonexisting source named `src`. Current behavior of Dalec is to process as normal not raising any issue of possible patches not being applied to an actual source or that `src` is no existing. 

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
