### ISSUE TITLE
overridable COMMIT during shell exec

### ISSUE THREAD

**Issue by sozercan** [Azure/dalec#20]
```
  src:
    ref: docker-image://mcr.microsoft.com/oss/go/microsoft/golang:1.21
    path: /build
    cmd:
      dir: /build/src
      sources:
        -
          copy: true
          path: /build/src
          spec:
            ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver.git#${COMMIT}
            filters:
              excludes:
                - .git
                - .github
                - Dockerfile
                - .dockerignore
                - _output
                - frontend/mariner2/test
      steps:
        - command: go mod download
          env:
            GOMODCACHE: /build/gomodcache
```
