### ISSUE TITLE
[BUG] Incorrect paths in %files section for a few types

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/dalec#265]
### Expected Behavior

I noticed a few unexpected results in the spec file and rpm after using the latest 0.4.0 tag.

1. If I don't specify a `name` for the artifact config for a binary, I just get the directory in the %files section.
2. The `name` property is ignored for config files and a few other newer types.

EXPECTED:

```
binaries:
    kubernetes/_output/bin/kubelet: {}
```

yields:

```
%files
%{_bindir}/kubelet
```

and:

```
configFiles:
    kubernetes-release/cmd/krel/templates/latest/kubelet/kubelet.env:
      name: kubelet
      subpath: sysconfig
```

yields:

```
%files
%config(noreplace) %{_sysconfdir}/sysconfig/kubelet
```

### Actual Behavior

```
binaries:
    kubernetes/_output/bin/kubelet: {}
```

yields:

```
%files
%{_bindir}
```

While:

```
configFiles:
    kubernetes-release/cmd/krel/templates/latest/kubelet/kubelet.env:
      name: kubelet
      subpath: sysconfig
```

yields:

```
%files
%config(noreplace) %{_sysconfdir}/sysconfig/kubelet.env
```

### Are you willing to submit PRs to contribute to this bug fix?

- [X] Yes, I am willing to implement it.
