### ISSUE TITLE
[REQ] generator to fetch a dynamically-generated list of `http` sources

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#294]
### What kind of request is this?

New feature

### What is your request or suggestion?

As an example, one of the [k3s build script](https://github.com/k3s-io/k3s/blob/c635818956f321d6d8a34a57c5a9fc98ad2d6607/scripts/download)s fetches a bunch of helm charts by using `curl`.

Currently, `dalec` does not have an easy way to dynamically generate a list of artifacts to fetch in this manner. Currently, the only way to do it is to create an `image` source that generates and fetches the list. There are some problems with this approach:
- The artifacts end up in the provenance data **only** in the form of the script that is run. And if, as in [this example](https://github.com/k3s-io/k3s/blob/c635818956f321d6d8a34a57c5a9fc98ad2d6607/scripts/download#L42C1-L45C5), the artifact URLs are generated, the actual URLs of the tarballs **will not end up in the provenance data**
- An irritating amount of boilerplate, which increases the friction of writing spec files and getting projects onboarded to `dalec`.

###Proposed Solution
```yaml
sources:
  charts:
    generate:
      - httpArtifactList:
           image: mcr.microsoft.com/oss/busybox:latest
           command: |
             for CHART_FILE in $(grep -rlF HelmChart manifests/ | xargs yq eval --no-doc .spec.chart | xargs -n1 basename); do
               CHART_NAME=$(echo $CHART_FILE | grep -oE '^(-*[a-z])+')
               URL="${CHARTS_URL}/${CHART_NAME}/${CHART_FILE}"
               echo "$URL" >> $DALEC_ARTIFACT_LIST
             done
    git:
      url: https://github.com/k3s-io/k3s.git
      commit: v1.30.0+k3s1
```

In the above example, the script in `sources.charts.generate[0].httpArtifactList.command` will be run within the container specified by `sources.charts.generate[0].httpArtifactList.image`. The list of artifacts will be generated by the script, and the final list will be contained in a file, at location `$DALEC_ARTIFACT_LIST`. That file will have one artifact URL per line, and nothing else.

This file will be read by dalec, and a `SourceHTTP` struct will be created for each line in the `$DALEC_ARTIFACT_LIST`. These can be added to the sources in the same way that the `gomod` generator adds the go mods to the sources.

### Are you willing to submit PRs to contribute to this feature request?

- [X] Yes, I am willing to implement it.
