### ISSUE TITLE
[REQ] patches should not duplicate the path

### ISSUE THREAD

**Issue by sozercan** [Azure/dalec#341]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

```
sources:
  foo:
    git:
      url: https://github.com/foo/foo.git
      commit: ${COMMIT}
      keepGitDir: true
    generate:
      - gomod: {}
  foo-patches:
    context: {}
    includes:
      - specs/foo/patches/bar.patch

patches:
  foo:
    - source: foo-patches
      path: specs/foo/patches/bar.patch
```

today, we are duplicating the `path` in both sources and patches, can we make eliminate the path if source is defined?

```
patches:
  foo:
    - source: foo-patches
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
