### ISSUE TITLE
[REQ] Allow targets section to reference built-in frontend

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#370]
### What kind of request is this?

None

### What is your request or suggestion?

We currently have a targets section like so:

```yaml
targets:
  azlinux3:
    // target-specific stuff
```

We can also add a custom target and reference an external frontend to handle building it:

```yaml
targets:
  custom:
    frontend:
      image: my.image:latest
```

But we can't create a custom target and tell it to use the built-in implementation.
This would be useful when you need to use the same underlying builder implementation but have some slight variances under a different target name

```yaml
targets:
  windowscross:
    // target-specific stuff
  windows-host-process:
    builder: windowscross
    image:
      base: <custom base>
```

Or probably more accurately:

```yaml
targets:
  windows:
    builder: windowscross
  windows-host-process:
    builder: windowscross
    image:
      base: <custom base>
```

Alternatively this could get added to the `frontend` section

```yaml
targets:
  windows-host-process:
    frontend:
      internal: windowscross
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
