### ISSUE TITLE
[REQ] Support multi-module repos for gomod generator

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#392]
### What kind of request is this?

New feature

### What is your request or suggestion?

Currently the gomod generator only supports generating gomods for a single module.
In order to have multiple modules one would have to define this as multiple sources.

I propose we add a field to the gomod generator type to allow specifying multiple module paths to generate from a single source.

Example:

```yaml
source:
  git:
    url: https://github.com/some/repo
    commit: v42.0.0
    generate:
      gomod:
        paths:
          - .
          - some/subpath
          - some/other/subpath
```

Where the implied default with no paths are specified is the working directory, e.g. `["."]`

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by DannyBrito** [comment]
q: the `generate` struct already has a `subpath` field https://github.com/DannyBrito/dalec/blob/main/spec.go#L316. How should this be handled with this need addition of multi gomod gen?
- Should it be ignored? Maybe we update this field to be the array for the submods?
- Does this field have a different purpose?

If we were to update this field, it could look something like:
```yml
source:
  git:
    url: https://github.com/some/repo
    commit: v42.0.0
    generate:
      paths:
          - .
          - some/subpath
          - some/other/subpath
      gomod:
```
