### ISSUE TITLE
[REQ] Allow specifying patches as a field on the source definition

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#393]
### What kind of request is this?

None

### What is your request or suggestion?

Today, patches are specified separately from sources, e.g.

```yaml
sources:
  src0:
    # source def
  patch0:
    # source def

patches:
  src0: # Name of the source to patch
    - source: patch0 # Name of the patch source
      path: path/to/patch # Path inside patch source
```

I propose we allow adding patches as a nested object on the source, like so:

```yaml
sources:
  src0:
    # source def
    patches:
      - context: {} # Can be any source type
        path: path/to/patch
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by DannyBrito** [comment]
would this meaning drop support of main `patches` section? or support both?

**Comment by DannyBrito** [comment]
I haven't looked into this yet, but is the following a valid approach?

To support this new syntax while maintaining backwards compatibility, during validation and parsing/filling defaults in the spec, we could convert this new syntax into the current sources block for each of these patches. Additionally, we need to add the required patches block with the corresponding sources. So, given this:

```yml
sources:
  src0:
    # source def
    patches:
      - context: {} # Can be any source type
        path: path/to/patch
```
Behind the scenes, Dalec will convert it to this:
```yml
sources:
  src0:
    # source def
  patch0:
    path: path/to/patch
    context: {}

patches:
  src0: # Name of the source to patch
    - source: patch0 # Name of the patch source
      path: path/to/patch # Path inside patch source
```
