### ISSUE TITLE
[BUG] jammy: Handling of multiple version constraints on a package is not the correct format

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#414]
### Expected Behavior

Given a spec with package constraints:

```yaml
dependencies:
  build:
    foo:
      version:
        - ">= 1.0"
        - "< 2.0"
```

The output in the control file looks like

```
Build-Depends: foo (>= 1.0, < 2.0)
```

This is the incorrect format and causes dependency resolution to fail.

### Actual Behavior

The correct format would be `foo (>= 1.0) | foo (<< 2.0)`

Also to note, the double carrot (`<<`) is not a typo... I think we have some handling for converting `<` to `<<` and `>` to `>>` but it may be insufficient (or maybe I'm mis-remembering altogether).

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
