### ISSUE TITLE
[REQ] Add support for per-command mounts on image+cmd type

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#437]
### What kind of request is this?

None

### What is your request or suggestion?

Right now you can add mounts to image sources like:

```yaml
sources:
  foo:
    image:
      cmd:
        mounts:
          # insert mounts here
```

The mounts get added to all steps defined in `cmd`.
The trouble here is now any command you run in the image is going to have its cache broken by any change to the mount content.
This means steps like installing some packages will always have to be re-run if the mount data changes even though the mount data does not affect that.

I propose that we can add support for adding mounts per cmd step.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
