### ISSUE TITLE
[BUG] apt: Repos keys must be readable by non-root user

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#467]
### Expected Behavior

Specifying a repo key should not require explicitly setting permissions on the key file(s).

### Actual Behavior

Keys must have the correct permissions already set (or defined in the source type).

### Steps To Reproduce

```yaml
extra_repos:
  - keys:
      msft.asc:
        http:
          url: https://packages.microsoft.com/keys/microsoft.asc
```

Building a spec with the above `extra_repos` on any apt-based distro will error with an unrelated error due to `apt` not being able to read the key.

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
