### ISSUE TITLE
[BUG] Multiple symlinks cannot be made to point to the same destination

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#489]
### Expected Behavior

You should be able to create multiple symlinks that point to the same location. For example:

```yaml
image:
  post:
    symlinks:
      - oldpath: /bin/busybox
        newpath: /usr/bin/sh
      - oldpath: /bin/busybox
         newpath: /usr/bin/test
```

### Actual Behavior

The spec format requires:

```yaml
image:
  post:
    symlinks:
      /bin/busybox:
        path: /usr/bin/sh
      /bin/busybox:
         path: /usr/bin/test
```

This causes a yaml parsing error at best, and silently overwrites the `/bin/busybox` map key at worst. 

### Steps To Reproduce

n/a, see above.

### Are you willing to submit PRs to contribute to this bug fix?

- [x] Yes, I am willing to implement it.
