### ISSUE TITLE
[BUG] Build args are not substituted into `image.base`

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#490]
### Expected Behavior

```yaml
args:
  BUSYBOX_TAG: 1.36
image:
  base: busybox:${BUSYBOX_TAG}
```

### Actual Behavior

With the above:
```
error handling requested build target "azlinux3/container": could not resolve base image config: error resolving base image config: docker.io/library/busybox:${BUSYBOX_VERSION}: not found
```

### Are you willing to submit PRs to contribute to this bug fix?

- [x] Yes, I am willing to implement it.
