### ISSUE TITLE
Remove magic strings in source defs

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#50]
Right now source defs have magic strings that get parsed like `docker-image://docker.io/library/redis:latest`, `build://`, and others.
These should not be neccessary instead opting for an approach where we have nullable values in the source definition struct itself.

Example for docker image:

Instead of

```yaml
sources:
  redis:
    ref: docker-image://docker.io/library/redis:latest
```

We can do:

```yaml
sources:
  redis:
    image:
      ref: docker.io/library/redis:latest
```

For builds:

Instead of:

```yaml
sources:
  someBuild:
    ref: build://
```

We can do:

```yaml
sources:
  someBuild:
    build:
      context: .
```

This makes the source defs significantly easier to read at the very least.
