### ISSUE TITLE
[BUG] windows platform is not set correctly

### ISSUE THREAD

**Issue by sozercan** [Azure/dalec#522]
### Expected Behavior

dalec produced windows image should have windows platform with version number

### Actual Behavior

https://oci.dag.dev/?image=docker.io%2Fsozercan%2Fwindows%3Atest

```
"platform": {
"architecture": "amd64",
"os": "linux"
}
```

### Steps To Reproduce

- given the spec below
```
# syntax=ghcr.io/azure/dalec/frontend:0.11

args:
  VERSION: 1.1.0
  COMMIT: 32022caedd6a177a7717aa8680cbe179e1045935
  REVISION: 1

name: fake-test-project
packager: foo
vendor: foo
license: Apache-2.0
website: https://github.com/golang/example
description: Fake project to use when testing workflows

version: ${VERSION}
revision: ${REVISION}

sources:
  example:
    generate:
      - gomod: {}
    git:
      url: https://github.com/golang/example.git
      commit: ${COMMIT}
      keepGitDir: true

build:
  env:
    VERSION: ${VERSION}
    GOPROXY: direct
  steps:
    - command: |
        set -e
        cd example/hello
        go build -o bin/hello .
        tree
        pwd

artifacts:
  binaries:
    example/hello/bin/hello: {}

targets:
  windowscross:
    dependencies:
      build:
        golang:
        git:
        make:
        gcc:
        tree:
```

- run the command:
`docker build -t foo/windows:test . -f windows.yaml --target windowscross --push`

- inspect pushed image for platform

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
