### ISSUE TITLE
[BUG] Dalec installs bash for seemingly no reason

### ISSUE THREAD

**Issue by Stevenjin8** [Azure/dalec#544]
### Expected Behavior

Take the following yaml

```yaml
# syntax=ghcr.io/azure/dalec/frontend:0.11

args:
  VERSION: 1
  REVISION: "1"

name: name
version: ${VERSION}
revision: ${REVISION}
license: Apache-2.0
description: "description"

dependencies:
  build:
    iana-etc: {}
    libmnl: {}
    libnftnl: {}
    iptables: {}

artifacts:
  binaries:
    /usr/sbin/xtables-nft-multi:
      subpath: ""
```

I would expect the resulting container to not have bash installed. But when I build it

```bash
docker build -t spec -f spec.yaml --progress plain --target azlinux3/container .
```

and run the container, `bash` is included

```bash
13:09:26 /home/sj/dalec-build-defs2 $ docker run --rm -it --entrypoint bash spec
root [ / ]#
```

However, if I get rid of the single binary

```
# syntax=ghcr.io/azure/dalec/frontend:0.11

args:
  VERSION: 1
  REVISION: "1"

name: name
version: ${VERSION}
revision: ${REVISION}
license: Apache-2.0
description: "description"

dependencies:
  build:
    iana-etc: {}
    libmnl: {}
    libnftnl: {}
    iptables: {}

artifacts:
  binaries: {}
```

and build it as before, `bash` is not installed in the container

```bash
$ docker run --rm -it --entrypoint bash spec
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "bash": executable file not found in $PATH: unknown.
```

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
