### ISSUE TITLE
[REQ] Resolve args in patch includes and sources

### ISSUE THREAD

**Issue by grnmeira** [Azure/dalec#606]
### What kind of request is this?

None

### What is your request or suggestion?

Given a variable/arg introduced in the "args" section, it'd be nice to be able to solve those variables/args inside the "includes" and "path" fields for sources and patches.

```
args:
  VERSION: 1.34.0
  COMMIT: ca8ab7f9ac873c8df1dd53a938a1f8dad1e33521
  REVISION: 1
...
sources:
  envoy:
    git:
      url: https://github.com/myproject
      commit: ${COMMIT}
      keepGitDir: true
  localPatches:
    context: {}
    includes:
      - specs/envoyproxy/myproject/${VERSION}/*

patches:
  envoy:
    - source: localPatches
      path: specs/envoyproxy/myproject/${VERSION}/*
...
```

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.
