### ISSUE TITLE
[BUG] generate docs are incorrect

### ISSUE THREAD

**Issue by Stevenjin8** [Azure/dalec#643]
### Expected Behavior

https://azure.github.io/dalec/sources/#gomod

```yaml
sources:
  md2man:
    git:
        url: https://github.com/cpuguy83/go-md2man.git
        commit: v2.1.0
    generate:
        subpath: "" # path inside the source to use as the root for the generator
        gomod: {} # Generates a go module cache to cache dependencies
```

the value of the generate key should be a list

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.
