### ISSUE TITLE
bug: rpm: Envs for individual build steps do not support multiple commands

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#70]
Example spec:

```yaml
build:
  steps:
    -
      command: |
         echo amazing things
         echo more amazing things
      env:
         FOO: bar
```

This yields something along the lines of this in the RPM spec:

```bash
FOO=bar echo amzthings
echo more amazing things
```

This should be something along the lines of

```bash
(
  export FOO=bar
  echo amazing things
  echo more amazing things
)
```
