### ISSUE TITLE
Test packages are not installed

### ISSUE THREAD

**Issue by cpuguy83** [Azure/dalec#75]
Somewhere along the way the ability to install packages just for tests got removed.

In the spec you can define test dependences:

```yaml
dependencies:
  test:
    - foo
    - bar
```

These get installed only the environment setup for executing tests for test specific dependencies.
