### ISSUE TITLE
Consider Changing `path` property in source spec

### ISSUE THREAD

**Issue by adamperlin** [Azure/dalec#79]
Sources can have an output path property, such as:

```
    gomods: # This is required when the build environment does not allow network access. This downloads all the go modules.
    path: /build/gomodcache # This is the path we will be extracing after running the command below.
    image:
      ref: mcr.microsoft.com/oss/go/microsoft/golang:1.21
      cmd:
     ...
```
However, in my opinion `path` here is a little ambiguous in the spec for new users of dalec without the added comment that path is where we are extracting **from**.  I would propose changing the name of  `path` to `target_path` or something similar, to make it clearer that the state which is extracted from the source is what is under the `path`. @cpuguy83 @pmengelbert do you have any thoughts?
